name: build-all

# Controls when the action will run. 
on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: 6.0.x
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-windows:
    # The type of runner that the job will run on
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./App

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - uses: microsoft/setup-msbuild@v1
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Restore NuGet packages
        run: nuget restore App.sln
          
      - name: Begin Sonar scan
        run: |
          echo ${pwd}
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /o:vladimirpetukhov /k:vladimirpetukhov_Musement_CLI /d:sonar.login=${{ secrets.SONAR_TOKEN }} /d:sonar.host.url=https://sonarcloud.io
     
      - name: Build Api 
        run: dotnet build App.sln       

      - name: End Sonar scan
        run: |
         cd ./App
          dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }} 